guns:
  swagger-open: true                #是否开启swagger (true/false)
  kaptcha-open: false               #是否开启登录时验证码 (true/false)
  spring-session-open: false        #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  locked: false

server:
  port: 8010
#  servlet:
#    context-path: /quick
  max-http-header-size: 10240

rest:
  img-url: http://127.0.0.1:6001/img
  img-path: /usr/local/tomcat-quick/img

efps:
  url: https://merchant.epaylinks.cn
  private-key-path: /usr/local/tomcat-quick/secret/efps.pfx
  public-key-path: /usr/local/tomcat-quick/secret/efps.cer
  sign-no: 20190115yhys01
  password: Epaylinks@EFPS2018
  customerCode: 5651300003039000
  order-notify-url: http://127.0.0.1:6001/quick/api/pay/epspOrderNofify
  split-notify-url: http://127.0.0.1:6001/quick/api/pay/epspSplitNofify
  mch-cash-notify-url: http://127.0.0.1:6001/quick/api/mch/epspMchCashNofify
  cash-rate: 50
  is-query-sub-customer: false
  is-service-fee: false

sum:
  password: sumpay
  private-key-path: /usr/local/tomcat-quick/secret/sum
  public-key-path: /usr/local/tomcat-quick/secret/sum/yixun.cer
  url: http://124.160.28.138:8180/entrance/gateway.htm
  domain: 127.0.0.1
  share-mer-no: s100000040
  cash_rate: 40
  min-order-amount: 500
  order-notify: http://127.0.0.1:6001/quick/api/vs/pay/orderNotify
  sign-notify: http://127.0.0.1:6001/quick/api/vs/mch/signNotify

sumbt:
  app-id: s100000040
  mer-no: s100000040
  sub-mer-no: 100453650
  password: sumpay
  private-key-path: /usr/local/tomcat-quick/secret/sumbt
  public-key-path: /usr/local/tomcat-quick/secret/sumbt/yixun.cer
  url: http://124.160.28.138:8180/entrance/gateway.htm
  domain: 127.0.0.1
  cost-rate: 0.0041
  cost-fee: 40
  min-order-amount: 500
  order-notify: http://127.0.0.1:6001/quick/api/vs/bt/pay/orderNotify

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.110.50.211:3306/quick_pay?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 648c064a886c800f
    filters: wall,mergeStat

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: quick.log
#多数据源情况的配置

